Cleanup bash scripts

diff --git a/bin/tcpsnitch b/bin/tcpsnitch
--- a/bin/tcpsnitch
+++ b/bin/tcpsnitch
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 set -o nounset
 # set -o xtrace
+
+# Name & version
 NAME="tcpsnitch"
 VERSION=0.1
 VERSION_STR="${NAME} version ${VERSION}"
@@ -17,43 +19,125 @@ OPT_T=1000
 OPT_U=0
 OPT_V=0
 
+# Exit on TERM signal
+trap "exit 1" TERM
+export TOP_PID=$$
+
+error() {
+    msg=$1
+    echo "${NAME}: ${msg}."
+    echo "Try '$0 -h' for more information."
+    kill -s TERM $TOP_PID
+}
+
+info() {
+    msg=$1
+    echo "${msg}."
+}
+
 usage() {
-        echo "Usage: tcpsnitch [-achv] [ -b <bytes> ] [ -d <dir>] [ -f <lvl> ]"
-        echo "                 [ -k <pkg> ] [ -l <lvl> ] [ -t <msec> ]"
-        echo "                 [ -u <usec> ] [ --version ] app <args>"
-        echo ""
-        echo "app         command/package to spy on."
-        echo "<args>      args to command."
-        echo "-a          instrument & launch app on connected android device."
-        echo "-b <bytes>  dump tcp_info every <bytes> (0 means NO dump, def 0)."
-        echo "-c          activate capture of pcap traces."
-        echo "-d <dir>    dir to save traces (defaults to random dir in /tmp)."
-        echo "-f <lvl>    verbosity of logs to file (0 to 5, defaults to 2)."
-        echo "-h          show this help text."
-        echo "-k <pkg>    kill instrumented android <pkg> and pull traces."
-        echo "-l <lvl>    verbosity of logs to stderr (0 to 5, defaults to 2)."
-        echo "-t <msec>   dump to JSON file every <msec> (def. 1000)."
-        echo "-u <usec>   dump tcp_info every <usec> (0 means NO dump, def 0)."
-        echo "-v          activate verbose output."
-        echo "--version   print tcpsnitch version."
+    echo "Usage: ${NAME} [-achv] [ -b <bytes> ] [ -d <dir>] [ -f <lvl> ]"
+    echo "                 [ -k <pkg> ] [ -l <lvl> ] [ -t <msec> ]"
+    echo "                 [ -u <usec> ] [ --version ] app <args>"
+    echo ""
+    echo "app         command/package to spy on."
+    echo "<args>      args to command."
+    echo "-a          instrument & launch app on connected android device."
+    echo "-b <bytes>  dump tcp_info every <bytes> (0 means NO dump, def 0)."
+    echo "-c          activate capture of pcap traces."
+    echo "-d <dir>    dir to save traces (defaults to random dir in /tmp)."
+    echo "-f <lvl>    verbosity of logs to file (0 to 5, defaults to 2)."
+    echo "-h          show this help text."
+    echo "-k <pkg>    kill instrumented android <pkg> and pull traces."
+    echo "-l <lvl>    verbosity of logs to stderr (0 to 5, defaults to 2)."
+    echo "-t <msec>   dump to JSON file every <msec> (def. 1000)."
+    echo "-u <usec>   dump tcp_info every <usec> (0 means NO dump, def 0)."
+    echo "-v          activate verbose output."
+    echo "--version   print ${NAME} version."
 }
 
 is_integer() {
-        [[ "$1" =~ ^[0-9]+$ ]]
+    [[ "$1" =~ ^[0-9]+$ ]]
 }
 
 assert_int() {
-        error_msg=$2
-        if ! is_integer "$1"; then
-                error "$error_msg"
-                exit 1
-        fi
+    error_msg=$2
+    if ! is_integer "$1"; then
+        error "$error_msg"
+    fi
 }
 
-error() {
-        msg=$1
-        echo "${NAME}: ${msg}."
-        echo "Try '${NAME} -h' for more information."
+validate_args_number() {
+    if [[ $# -lt 1 ]]; then
+        error "too few arguments"
+    fi
+}
+
+validate_executable() {
+    cmd=$1
+    if [ ${cmd:0:2} = "./" -o ${cmd:0:1} = "/" ]; then # $cmd is a path
+        if ! [[ -x "$cmd" ]]; then
+            error "invalid cmd: '$cmd' is not executable" 
+        fi
+    else
+        if ! which $cmd > /dev/null; then
+            error "invalid argument: '$cmd' is not in \$PATH"
+        fi
+    fi
+}
+
+get_android_package() {
+    if [[ $# -ne 1 ]]; then
+        error "missing package argument"
+    fi
+
+    package_name=$1
+    # Check that adb sees exactly 1 device
+    if [ $(adb devices | wc -l) -ne 3 ]; then
+        error "adb must see exactly 1 device"
+    fi
+
+    prefix="package:"
+    match=$(echo $(adb shell pm list packages | grep -m 1 -s "$package_name") | tr -d '\r')
+
+    # Check that package exists
+    if [ -z "$match" ]; then
+        error "invalid argument: package '$package_name' not found"
+    fi
+
+    __PACKAGE=${match#${prefix}}
+    info "Found Android package: '${__PACKAGE}'"
+}
+
+start_android_package() {
+    adb shell "monkey -p ${__PACKAGE} -c android.intent.category.LAUNCHER 1 >/dev/null"
+    info "Start package '${__PACKAGE}'"
+}
+
+kill_android_package() {
+    adb shell su -c am force-stop ${__PACKAGE}
+}
+
+pull_trace_for_android_package() {
+    tracesdir="/data/data/${__PACKAGE}/${NAME}"
+
+    if [[ ! $(adb shell su -c ls ${tracesdir}) ]]; then
+        error "no traces for '${__PACKAGE}'"
+    fi
+
+    info "Pulling trace from Android device..."
+
+    tmpdir=$(mktemp -d)
+    chmod 777 "$tmpdir"
+    adb shell su -c ls ${tracesdir} | while read -r line; do
+        trace=$(echo $line | tr -d '\r')
+        adb shell su -c mv "${tracesdir}/${trace}" "/data/${trace}"
+        adb shell su busybox chmod -R 777 "/data/${trace}"
+        adb pull "/data/${trace}" "${tmpdir}/${trace}" 2>/dev/null
+        adb shell su -c rm -rf "/data/${trace}"
+    done
+
+    info "Trace saved in $tmpdir"
 }
 
 parse_options() {
@@ -63,7 +147,7 @@ parse_options() {
             -) # Trick to parse long options with getopts.
                 case "$OPTARG" in
                     version)
-                        echo ${VERSION_STR}
+                        info $VERSION_STR
                         exit 0
                         ;;
                 esac
@@ -81,7 +165,6 @@ parse_options() {
             d)
                 if [[ ! -d "$OPTARG" ]] ; then
                     error "invalid -d argument: '$OPTARG'"
-                    exit 1
                 fi
                 OPT_D=$OPTARG
                 ;;
@@ -94,10 +177,10 @@ parse_options() {
                 exit 0
                 ;;
             k)
-                cd $(dirname $(realpath $0))
-                ./kill_package $2   
-                ./pull_traces $2
-                exit 0 
+                get_android_package $2
+                kill_android_package
+                pull_trace_for_android_package
+                exit 0
                 ;;
             l)
                 assert_int "$OPTARG" "invalid -l argument: '$OPTARG'" 
@@ -114,34 +197,11 @@ parse_options() {
             v)
                 OPT_V=$((OPT_V+1))
                 ;;
-               \?)     
+            \?)
                 error "invalid option"
-                exit 1
                 ;;
         esac
     done
-}
-
-validate_args_number() {
-    if [[ $# -lt 1 ]]; then
-        error "too few arguments"
-        exit 1
-    fi
-}
-
-validate_executable() {
-    cmd=$1
-    if [ ${cmd:0:2} = "./" -o ${cmd:0:1} = "/" ]; then # $cmd is a path
-        if ! [[ -x "$cmd" ]]; then
-            error "invalid cmd: '$cmd' is not executable" 
-            exit 1
-        fi
-    else
-        if ! which $cmd > /dev/null; then
-            error "invalid argument: '$cmd' is not in \$PATH"
-            exit 1
-        fi
-    fi
 }
 
 ###################
@@ -154,7 +214,7 @@ parse_options $@
 shift $((OPTIND - 1))
 
 validate_args_number $@
-    
+
 command=$1
 
 if [ $OPT_A -eq "1" ]; then
@@ -164,46 +224,42 @@ if [ $OPT_A -eq "1" ]; then
     cd $(dirname $(realpath $0))
 
     # Validate package
-    exec 3>&2
-    package=$(./get_package $command 2>&3)
-    if [ $? -eq 1 ]; then
-        exit 1;
-    fi
-    echo "Setting up tcpsnitch for: '${package}'"
-    adb shell su -c am force-stop ${package}
+    get_android_package $command
 
-    # Desactivate Selinux 
+    # Kill package if running
+    kill_android_package
+
+    # Desactivate Selinux
     adb shell su -c setenforce 0
 
     # Create logs dir
-    OPT_D="/data/data/${package}/tcpsnitch"
-    adb shell su -c rm -rf ${OPT_D} 
+    OPT_D="/data/data/${__PACKAGE}/${NAME}"
+    adb shell su -c rm -rf ${OPT_D}
     adb shell su -c mkdir -m 777 -p ${OPT_D}
 
     # Write meta data
     meta_dir="$OPT_D/meta"
-    adb shell mkdir $meta_dir 
-    adb shell "echo $package > $meta_dir/app"
-    adb shell "echo $package > $meta_dir/cmd"
-    adb shell "uname -r > $meta_dir/kernel"
-    adb shell "uname -m > $meta_dir/machine"
-    adb shell "sysctl net > $meta_dir/net 2>/dev/null"
-    adb shell "echo android > $meta_dir/os"
-    adb shell "echo $VERSION > $meta_dir/version"
+    adb shell mkdir $meta_dir
+    adb shell "echo ${__PACKAGE} > ${meta_dir}/app"
+    adb shell "echo ${__PACKAGE} > ${meta_dir}/cmd"
+    adb shell "uname -r > ${meta_dir}/kernel"
+    adb shell "uname -m > ${meta_dir}/machine"
+    adb shell "sysctl net > ${meta_dir}/net 2>/dev/null"
+    adb shell "echo android > ${meta_dir}/os"
+    adb shell "echo ${VERSION} > ${meta_dir}/version"
 
-    # Update lib
-    BASE_PROP="be.ucl.tcpsnitch"
-    LIB="android-libtcpsnitch.so"
+    # Upload lib
+    BASE_PROP="be.ucl.${NAME}"
+    LIB="android-lib${NAME}.so"
     LIBPATH="/data"
-
     adb shell su -c chmod 777 /data
     adb shell rm -f "${LIBPATH}/${LIB}"
-    echo "Uploading library to ${LIBPATH}/${LIB}"
-    adb push ${LIB} ${LIBPATH}
+    info "Uploading ${NAME} library to ${LIBPATH}/${LIB}"
+    adb push ${LIB} ${LIBPATH} 2>/dev/null
 
     # Properties are limited to 32 chars includind the NULL byte.
     # With "wrap." being 5 chars, we have 26 chars left the app name.
-    adb shell setprop wrap.${package:0:26} LD_PRELOAD="${LIBPATH}/${LIB}"
+    adb shell setprop wrap.${__PACKAGE:0:26} LD_PRELOAD="${LIBPATH}/${LIB}"
     adb shell setprop "$BASE_PROP.opt_b" "$OPT_B"
     adb shell setprop "$BASE_PROP.opt_c" "$OPT_C"
     adb shell setprop "$BASE_PROP.opt_d" "$OPT_D"
@@ -213,9 +269,9 @@ if [ $OPT_A -eq "1" ]; then
     adb shell setprop "$BASE_PROP.opt_u" "$OPT_U"
     adb shell setprop "$BASE_PROP.opt_v" "$OPT_V"
 
-    # Start app
-    adb shell monkey -p $package -c android.intent.category.LAUNCHER 1
-else 
+    start_android_package
+    info "Execute './${NAME} -k ${command}' to terminate the capture"
+else
     #########
     # Linux #
     #########
