Do not upload trace when cmd exists abnormally

diff --git a/bin/tcpsnitch b/bin/tcpsnitch
--- a/bin/tcpsnitch
+++ b/bin/tcpsnitch
@@ -341,14 +341,19 @@ tcpsnitch_linux() {
     TCPSNITCH_OPT_U=$OPT_U \
     TCPSNITCH_OPT_V=$OPT_V \
     LD_PRELOAD="./${I386_LIB} ./${AMD64_LIB}" "$@" 4>&1 3>&2
-
     # Note that tcpsnitch opens 2 streams to file descriptors 3 and 4. These new
     # streams serve as the new stdout/stderr for tcpsnitch. This allows us to
     # distinguish stdout/stderr of tcpsnitch & of the traced process.
+    declare cmd_exit_status=$?
 
     info "Trace saved in ${OPT_D}"
-    zip_trace
-    upload_trace
+    if [[ "$cmd_exit_status" == 0 ]]; then
+        zip_trace
+        upload_trace
+    else
+        error "Traced command exited abnormally with error code '$cmd_exit_status'"
+        exit 1
+    fi
 }
 
 ###############################################################################
