Refactor bin/tcpsnitch & add opt_d, opt_n, opt_p for Android

diff --git a/bin/tcpsnitch b/bin/tcpsnitch
--- a/bin/tcpsnitch
+++ b/bin/tcpsnitch
@@ -1,28 +1,34 @@
 #!/usr/bin/env bash
 set -o nounset
-#set -o xtrace
+# set -o xtrace
 
-# Modify this to change name, version & libs path
+###############################################################################
+
+##############
+# Constants #
+############
+
 readonly NAME="tcpsnitch"
 readonly VERSION=0.1
 readonly VERSION_STR="${NAME} version ${VERSION}"
-#readonly SERVER="192.168.99.101:3000"
-readonly SERVER="ns328523.ip-37-187-114.eu"
+readonly SERVER="192.168.99.100:3000"
+#readonly SERVER="ns328523.ip-37-187-114.eu"
+readonly SERVER_ENDPOINT="http://${SERVER}/app_traces"
 readonly I386_LIB="lib${NAME}.so.${VERSION}-i386"
 readonly AMD64_LIB="lib${NAME}.so.${VERSION}-x86_64"
 readonly ARM_LIB="lib${NAME}.so.${VERSION}-arm"
 readonly LINUX_GIT_HASH="linux_git_hash"
 readonly ANDROID_GIT_HASH="android_git_hash"
-readonly TOP_PID=$$
 readonly SCRIPT_DIR=$(dirname "$(realpath "$0")")
 readonly PROP_PREFIX="be.ucl.${NAME}"
 readonly HIDDEN_ERRORS="wrong ELF class: ELFCLASS32|wrong ELF class: ELFCLASS64"
+readonly TOP_PID=$$
 
-# Modify this this to change option default values
+# Option default values
 OPT_A=0
 OPT_B=0
 OPT_C=0
-OPT_D="-" # Need non-empty value to fit OPTIONS_VALUES array
+OPT_D=""
 OPT_F=2
 OPT_L=1
 OPT_N=0
@@ -31,29 +37,23 @@ OPT_T=1000
 OPT_U=0
 OPT_V=0
 
+# Options saved in meta files
 META_OPTIONS_NAMES=(opt_b opt_f opt_u)
 META_OPTIONS_COUNT=${#META_OPTIONS_NAMES[@]}
+META_OPTIONS_VALS=($OPT_B $OPT_F $OPT_U)
 
-# Exit on TERM signal
-trap "exit 1" TERM
+###############################################################################
 
-error() {
-    declare msg="$1"
-    echo "${NAME}: ${msg}."
-    echo "Try '${NAME} -h' for more information."
-    kill -s TERM $TOP_PID
-}
-
-info() {
-    echo "${1}."
-}
+############
+# Options #
+##########
 
 usage() {
     echo "Usage: ${NAME} [-achpv] [ -b <bytes> ] [ -d <dir>] [ -f <lvl> ]"
     echo "                 [ -k <pkg> ] [ -l <lvl> ] [ -t <msec> ]"
-    echo "                 [ -u <usec> ] [ --version ] app <args>"
+    echo "                 [ -u <usec> ] [ --version ] <app> [<args>]"
     echo ""
-    echo "app         cmd/package to spy on."
+    echo "<app>       cmd/package to spy on."
     echo "<args>      args to cmd."
     echo "-a          instrument & launch app on connected android device."
     echo "-b <bytes>  dump tcp_info every <bytes> (0 means NO dump, def 0)."
@@ -71,6 +71,91 @@ usage() {
     echo "--version   print ${NAME} version."
 }
 
+parse_options() {
+    # Parse options
+    while getopts ":achnpvb:d:f:k:l:t:u:-:" opt; do
+        case "${opt}" in
+            -) # Trick to parse long options with getopts.
+                case "${OPTARG}" in
+                    version)
+                        info "${VERSION_STR}"
+                        exit 0
+                        ;;
+                esac
+                ;;
+            a)
+                OPT_A=1
+                ;;
+            b)
+                assert_int "${OPTARG}" "invalid -b argument: '${OPTARG}'" 
+                OPT_B=${OPTARG}
+                ;;
+            c)
+                OPT_C=1;
+                ;;
+            d)
+                if [[ ! -d "${OPTARG}" ]] ; then
+                    error "invalid -d argument: '${OPTARG}'"
+                fi
+                OPT_D=$(realpath "$OPTARG")
+                ;;
+            f)
+                assert_int "${OPTARG}" "invalid -f argument: '${OPTARG}'" 
+                OPT_F=${OPTARG}
+                ;;
+            h)
+                usage
+                exit 0
+                ;;
+            k)
+                tcpsnitch_android_teardown $@
+                exit 0
+                ;;
+            l)
+                assert_int "${OPTARG}" "invalid -l argument: '${OPTARG}'" 
+                OPT_L=${OPTARG}
+                ;;
+            n)
+                OPT_N=1
+                ;;
+            p)
+                OPT_P=1
+                ;;
+            u)
+                assert_int "${OPTARG}" "invalid -u argument: '${OPTARG}'" 
+                OPT_U=${OPTARG}
+                ;;
+            t)
+                assert_int "${OPTARG}" "invalid -t argument: '${OPTARG}'"
+                OPT_T=${OPTARG}
+                ;;
+            v)
+                OPT_V=$((OPT_V+1))
+                ;;
+            \?)
+                error "invalid option"
+                ;;
+        esac
+    done
+}
+
+###############################################################################
+
+############
+# Helpers #
+##########
+
+error() {
+    declare msg="$1"
+    echo "${NAME}: ${msg}."
+    echo "Try '${NAME} -h' for more information."
+    kill -s TERM $TOP_PID
+}
+
+info() {
+    echo "${1}."
+}
+
 is_integer() {
     [[ "$1" =~ ^[0-9]+$ ]]
 }
@@ -83,11 +168,72 @@ assert_int() {
     fi
 }
 
+cd_script_dir() {
+    cd "$SCRIPT_DIR" || exit "Could not cd to ${SCRIPT_DIR}"
+}
+
+assert_lib_present() {
+    declare lib="$1"
+    if [[ ! -f "$lib" ]]; then
+        error "${lib} missing! Reinstall ${NAME} (see README)"
+    fi
+}
+
 validate_args_number() {
     if [[ $# -lt 1 ]]; then
         error "too few arguments"
     fi
 }
+
+create_opt_d_dir() {
+    if [[ -z "$OPT_D" ]]; then
+        OPT_D=$(mktemp -d)
+        chmod 777 "$OPT_D"
+    fi
+}
+
+zip_trace() {
+    cd "${OPT_D}" || error "Could not cd to ${OPT_D}"
+    tar -czf archive.tar.gz ./*
+}
+
+upload_trace() {
+    if [[ $OPT_N -eq "1" ]]; then exit; fi
+
+    declare form="app_trace[archive]=@${OPT_D}/archive.tar.gz"
+
+    if [[ $OPT_P -eq "1" ]]; then
+        read -p "Workload decription (e.g. 'Opened app & navigated to google.com'): " workload
+
+        PS3='Select connectivity type: '
+        options=("wifi" "ethernet" "lte")
+        select connectivity in "${options[@]}"; do
+            case "$connectivity" in
+                "wifi"|"ethernet"|"lte")
+                    break
+                    ;;
+                *)
+                    echo "Invalid option"
+            esac
+        done
+
+        info "Uploading trace..."
+        if ! curl --connect-timeout 2 -F "$form" -F "app_trace[workload]=$workload" -F "app_trace[connectivity]=$connectivity" "$SERVER_ENDPOINT"; then
+            info "Failed to connect to ${SERVER}"
+        fi
+    else
+        info "Uploading trace..."
+        if ! curl --connect-timeout 2 -F "$form" "$SERVER_ENDPOINT"; then
+            info "Failed to connect to ${SERVER}"
+        fi
+    fi
+}
+
+###############################################################################
+
+####################
+# Android helpers #
+##################
 
 get_android_package() {
     declare package_name="$1"
@@ -129,211 +275,20 @@ pull_trace_for_android_package() {
         error "no traces for '${PACKAGE}'"
     fi
 
-    OPT_D=$(mktemp -d)
     info "Pulling trace from Android device..."
     adb shell su -c chown -R shell "$tracesdir"
     adb pull "$tracesdir" "$OPT_D" 2>/dev/null
     adb shell su -c rm -rf "$tracesdir"
-    info "Trace saved in ${OPT_D}"
+    info "Trace saved in $OPT_D"
 }
 
-zip_trace() {
-    cd "${OPT_D}" || error "Could not cd to ${OPT_D}"
-    tar -czf archive.tar.gz ./*
-}
+###############################################################################
 
-upload_trace() {
-    if [[ $OPT_N -eq "1" ]]; then exit; fi
+##########
+# Linux #
+########
 
-    form="app_trace[archive]=@${OPT_D}/archive.tar.gz"
-    pedantic_form=""
-
-    if [[ $OPT_P -eq "1" ]]; then
-        read -p "Workload decription (e.g. 'Opened app & navigated to google.com'): " workload
-
-        PS3='Select connectivity type: '
-        options=("wifi" "ethernet" "lte")
-        select connectivity in "${options[@]}"; do
-            case "$connectivity" in
-                "wifi"|"ethernet"|"lte")
-                    break
-                    ;;
-                *)
-                    echo "Invalid option"
-            esac
-        done
-
-        info "Uploading trace..."
-        if ! curl --connect-timeout 2 -F "$form" -F "app_trace[workload]=$workload" -F "app_trace[connectivity]=$connectivity" "http://${SERVER}/app_traces"; then
-            info "Failed to connect to ${SERVER}"
-        fi
-    else
-        info "Uploading trace..."
-        if ! curl --connect-timeout 2 --progress-bar -F "$form" "http://${SERVER}/app_traces"; then
-            info "Failed to connect to ${SERVER}"
-        fi
-    fi
-}
-
-android_stop() {
-    get_android_package "${2}"
-    kill_android_package
-    pull_trace_for_android_package
-    zip_trace
-    upload_trace
-}
-
-parse_options() {
-    # Parse options
-    while getopts ":achnpvb:d:f:k:l:u:t:-:" opt; do
-        case "${opt}" in
-            -) # Trick to parse long options with getopts.
-                case "${OPTARG}" in
-                    version)
-                        info "${VERSION_STR}"
-                        exit 0
-                        ;;
-                esac
-                ;;
-            a)
-                OPT_A=1
-                ;;
-            b)
-                assert_int "${OPTARG}" "invalid -b argument: '${OPTARG}'" 
-                OPT_B=${OPTARG}
-                ;;
-            c)
-                OPT_C=1;
-                ;;
-            d)
-                if [[ ! -d "${OPTARG}" ]] ; then
-                    error "invalid -d argument: '${OPTARG}'"
-                fi
-                OPT_D=${OPTARG}
-                ;;
-            f)
-                assert_int "${OPTARG}" "invalid -f argument: '${OPTARG}'" 
-                OPT_F=${OPTARG}
-                ;;
-            h)
-                usage
-                exit 0
-                ;;
-            k)
-                android_stop $@
-                exit 0
-                ;;
-            l)
-                assert_int "${OPTARG}" "invalid -l argument: '${OPTARG}'" 
-                OPT_L=${OPTARG}
-                ;;
-            n)
-                OPT_N=1
-                ;;
-            p)
-                OPT_P=1
-                ;;
-            u)
-                assert_int "${OPTARG}" "invalid -u argument: '${OPTARG}'" 
-                OPT_U=${OPTARG}
-                ;;
-            t)
-                assert_int "${OPTARG}" "invalid -t argument: '${OPTARG}'"
-                OPT_T=${OPTARG}
-                ;;
-            v)
-                OPT_V=$((OPT_V+1))
-                ;;
-            \?)
-                error "invalid option"
-                ;;
-        esac
-    done
-}
-
-###################
-# Start of script #
-###################
-
-parse_options "$@"
-OPTIONS_VALS=($OPT_A $OPT_B $OPT_C $OPT_D $OPT_F $OPT_L $OPT_N $OPT_T $OPT_U $OPT_V)
-
-# Consume option args
-shift $((OPTIND - 1))
-
-validate_args_number "$@"
-
-cmd="$1"
-
-if [[ $OPT_A -eq "1" ]]; then
-    ###########
-    # Android #
-    ###########
-    # Test if Android lib is present
-    cd "$SCRIPT_DIR" || exit "Could not cd to ${SCRIPT_DIR}"
-    if [[ ! -f ${ARM_LIB} ]]; then
-        error "${ARM_LIB} missing! Reinstall ${NAME} for Android (see README)"
-    fi
-
-    # Validate package
-    get_android_package "$cmd"
-
-    # Kill package if running
-    kill_android_package
-
-    # Desactivate Selinux
-    adb shell su -c setenforce 0
-
-    # Create logs dir
-    OPT_D="/data/data/${PACKAGE}/${NAME}"
-    adb shell su -c rm -rf "$OPT_D"
-    adb shell su -c mkdir -m 777 -p "$OPT_D"
-
-    # Write meta data
-    meta_dir="$OPT_D/meta"
-    adb shell mkdir "$meta_dir"
-    adb shell "echo ${PACKAGE} > ${meta_dir}/app"
-    adb shell "echo ${PACKAGE} > ${meta_dir}/cmd"
-    adb shell "uname -r > ${meta_dir}/kernel"
-    adb shell "uname -m > ${meta_dir}/machine"
-    adb shell "sysctl net > ${meta_dir}/net 2>/dev/null"
-    adb shell "echo android > ${meta_dir}/os"
-    adb shell "echo ${VERSION} > ${meta_dir}/version"
-    adb shell "echo ${PACKAGE} > ${meta_dir}/app"
-#    git_hash=$(cat "$ANDROID_GIT_HASH")
-    adb shell "echo $(cat "$ANDROID_GIT_HASH") > ${meta_dir}/git_hash"
-    adb shell "hostid > ${meta_dir}/host_id"
-    adb shell "dumpsys package ${PACKAGE} | grep versionName > ${meta_dir}/app_version"
-    for i in $(seq 0 $((${META_OPTIONS_COUNT}-1))); do
-        adb shell "echo ${OPTIONS_VALS[$i]} > ${meta_dir}/${META_OPTIONS_NAMES[$i]}"
-    done
-
-    # Upload lib
-    LIBPATH="/data"
-    adb shell su -c chmod 777 /data
-    adb shell rm -f "${LIBPATH}/${ARM_LIB}"
-    info "Uploading ${NAME} library to ${LIBPATH}/${ARM_LIB}"
-    adb push ${ARM_LIB} ${LIBPATH} 2>/dev/null
-
-    # Properties are limited to 32 chars includind the NULL byte.
-    # With "wrap." being 5 chars, we have 26 chars left the app name.
-    adb shell setprop wrap."${PACKAGE:0:26}" LD_PRELOAD="${LIBPATH}/${ARM_LIB}"
-    adb shell setprop "${PROP_PREFIX}.opt_b" "$OPT_B"
-    adb shell setprop "${PROP_PREFIX}.opt_c" "$OPT_C"
-    adb shell setprop "${PROP_PREFIX}.opt_d" "$OPT_D"
-    adb shell setprop "${PROP_PREFIX}.opt_f" "$OPT_F"
-    adb shell setprop "${PROP_PREFIX}.opt_l" "$OPT_L"
-    adb shell setprop "${PROP_PREFIX}.opt_t" "$OPT_T"
-    adb shell setprop "${PROP_PREFIX}.opt_u" "$OPT_U"
-    adb shell setprop "${PROP_PREFIX}.opt_v" "$OPT_V"
-
-    start_android_package
-    info "Execute './${NAME} -k ${cmd}' to terminate the capture"
-else
-    #########
-    # Linux #
-    #########
-    # Validate cmd
+tcpsnitch_linux() {
     if [ -f "$cmd" ]; then
         # Resolve absolute path for $1 & update positional parameter accordingly
         cmd=$(realpath "$cmd")
@@ -349,27 +304,19 @@ else
     fi
 
     # Test if libs are present
-    cd "$SCRIPT_DIR" || error "Could not cd to ${SCRIPT_DIR}"
-    if [[ ! -f ${I386_LIB} ]]; then
-        error "${I386_LIB} missing! Reinstall ${NAME}"
-    fi
-    if [[ ! -f ${AMD64_LIB} ]]; then
-        error "${AMD64_LIB} missing! Reinstall ${NAME}"
-    fi
+    cd_script_dir
+    assert_lib_present "$I386_LIB"
+    assert_lib_present "$AMD64_LIB"
 
-    # Create logs dir if option -d not used
-    if [[ "-" == "$OPT_D" ]]; then
-        OPT_D=$(mktemp -d)
-        chmod 777 "$OPT_D"
-    fi
+    create_opt_d_dir
 
     # Extract app (split on '/' and take last)
     # Global replace (//) in $1 of / (escaped) by ' ' & interpret as array
-    array=(${1//\// });
-    app=${array[-1]}
+    declare array=(${1//\// });
+    declare app=${array[-1]}
 
     # Write meta data
-    meta_dir="$OPT_D/meta"
+    declare meta_dir="$OPT_D/meta"
     mkdir "$meta_dir"
     echo "$app" > "${meta_dir}/app"
     echo "$@" > "${meta_dir}/cmd"
@@ -382,9 +329,8 @@ else
     hostid > "${meta_dir}/host_id"
     "$1" --version 2>/dev/null >"${meta_dir}/app_version"
     for i in $(seq 0 $((${META_OPTIONS_COUNT}-1))); do
-        echo "${OPTIONS_VALS[$i]}" > ${meta_dir}/${META_OPTIONS_NAMES[$i]}
+        echo "${META_OPTIONS_VALS[$i]}" > ${meta_dir}/${META_OPTIONS_NAMES[$i]}
     done
-
 
     TCPSNITCH_OPT_B=$OPT_B \
     TCPSNITCH_OPT_C=$OPT_C \
@@ -397,11 +343,109 @@ else
     LD_PRELOAD="./${I386_LIB} ./${AMD64_LIB}" "$@" 4>&1 3>&2
 
     # Note that tcpsnitch opens 2 streams to file descriptors 3 and 4. These new
-    # streams serve as the new stdout/stderr for tcpsnitch. This allows us to 
+    # streams serve as the new stdout/stderr for tcpsnitch. This allows us to
     # distinguish stdout/stderr of tcpsnitch & of the traced process.
 
     info "Trace saved in ${OPT_D}"
     zip_trace
     upload_trace
-fi
+}
 
+###############################################################################
+
+############
+# Android #
+##########
+
+tcpsnitch_android() {
+    cd_script_dir
+    assert_lib_present "$ARM_LIB"
+    get_android_package "$cmd"
+    kill_android_package
+    create_opt_d_dir
+
+    # Desactivate Selinux
+    adb shell su -c setenforce 0
+
+    # Create logs dir
+    declare LOGS_DIR="/data/data/${PACKAGE}/${NAME}"
+    adb shell su -c rm -rf "$LOGS_DIR"
+    adb shell su -c mkdir -m 777 -p "$LOGS_DIR"
+
+    # Write meta data
+    declare meta_dir="$LOGS_DIR/meta"
+    adb shell mkdir "$meta_dir"
+    adb shell "echo ${PACKAGE} > ${meta_dir}/app"
+    adb shell "echo ${PACKAGE} > ${meta_dir}/cmd"
+    adb shell "uname -r > ${meta_dir}/kernel"
+    adb shell "uname -m > ${meta_dir}/machine"
+    adb shell "sysctl net > ${meta_dir}/net 2>/dev/null"
+    adb shell "echo android > ${meta_dir}/os"
+    adb shell "echo ${VERSION} > ${meta_dir}/version"
+    adb shell "echo ${PACKAGE} > ${meta_dir}/app"
+    adb shell "echo $(cat "$ANDROID_GIT_HASH") > ${meta_dir}/git_hash"
+    adb shell "hostid > ${meta_dir}/host_id"
+    adb shell "dumpsys package ${PACKAGE} | grep versionName > ${meta_dir}/app_version"
+    for i in $(seq 0 $((${META_OPTIONS_COUNT}-1))); do
+        adb shell "echo ${META_OPTIONS_VALS[$i]} > ${meta_dir}/${META_OPTIONS_NAMES[$i]}"
+    done
+
+    # Upload lib
+    LIBPATH="/data"
+    adb shell su -c chmod 777 /data
+    adb shell rm -f "${LIBPATH}/${ARM_LIB}"
+    info "Uploading ${NAME} library to ${LIBPATH}/${ARM_LIB}"
+    adb push ${ARM_LIB} ${LIBPATH} 2>/dev/null
+
+    # Properties are limited to 32 chars includind the NULL byte.
+    # With "wrap." being 5 chars, we have 26 chars left the app name.
+    adb shell setprop wrap."${PACKAGE:0:26}" LD_PRELOAD="${LIBPATH}/${ARM_LIB}"
+    adb shell setprop "${PROP_PREFIX}.opt_b" "$OPT_B"
+    adb shell setprop "${PROP_PREFIX}.opt_d" "$LOGS_DIR"
+    adb shell setprop "${PROP_PREFIX}.opt_f" "$OPT_F"
+    adb shell setprop "${PROP_PREFIX}.opt_l" "$OPT_L"
+    adb shell setprop "${PROP_PREFIX}.opt_t" "$OPT_T"
+    adb shell setprop "${PROP_PREFIX}.opt_u" "$OPT_U"
+    adb shell setprop "${PROP_PREFIX}.opt_v" "$OPT_V"
+
+    # Those properties are used by this bash script only. We set them to
+    # retrieve them on -k.
+    adb shell setprop "${PROP_PREFIX}.opt_d_k" "$OPT_D"
+    adb shell setprop "${PROP_PREFIX}.opt_n_k" "$OPT_N"
+    adb shell setprop "${PROP_PREFIX}.opt_p_k" "$OPT_P"
+
+    start_android_package
+    info "Execute './${NAME} -k ${cmd}' to terminate the capture"
+}
+
+tcpsnitch_android_teardown() {
+    OPT_D=$(adb shell getprop "${PROP_PREFIX}.opt_d_k" | tr -d '\r')
+    OPT_N=$(adb shell getprop "${PROP_PREFIX}.opt_n_k" | tr -d '\r')
+    OPT_P=$(adb shell getprop "${PROP_PREFIX}.opt_p_k" | tr -d '\r')
+
+    get_android_package "${2}"
+    kill_android_package
+    pull_trace_for_android_package
+    zip_trace
+    upload_trace
+}
+
+###############################################################################
+
+################
+# MAIN SCRIPT #
+##############
+
+trap "exit 1" TERM
+
+parse_options "$@"
+shift $((OPTIND - 1))
+
+validate_args_number "$@"
+cmd="$1"
+
+if [[ $OPT_A -eq "1" ]]; then
+    tcpsnitch_android "$@"
+else
+    tcpsnitch_linux "$@"
+fi
